Final code (#223)
* Deleted unnecessary code

* Deleted more extraneous code

* Update app

* remove code

* Removed redundant, commented-out code (along with console logs)

* Fixed: ERROR in src/app/views/home/home.component.ts(335,1): error TS1005: '}' expected.

* Revert "Fixed: ERROR in src/app/views/home/home.component.ts(335,1): error TS1005: '}' expected."

This reverts commit d9ced0908cb1bf16935cc02ed243a0561c2a7844.

* Removed extraneous white spaces and bad indents

* Update README.md

* changed page size on performance and event management to 9