Revert "Fixed: ERROR in src/app/views/home/home.component.ts(335,1): error TS1005: '}' expected."
This reverts commit d9ced0908cb1bf16935cc02ed243a0561c2a7844.